language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - windows
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo test --verbose --features disabled
