[package]
name = "microprofile"
version = "0.0.1"
authors = ["Jonas Meyer <jonas.meyer@gmail.com>"]
edition = "2018"
build = "src/build.rs"

[features]
default = []
disabled = []

[build-dependencies]
cc = "1.0"
